# Generated by Django 5.1.5 on 2025-02-02 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_permission', models.CharField(max_length=200)),
                ('description_permission', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_profile', models.ImageField(blank=True, default='default.png', null=True, upload_to='image_profile', verbose_name='รูปภาพโปรไฟล์')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='ที่อยู่')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='เบอร์โทรศัพท์')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
