# Generated by Django 5.1.5 on 2025-02-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_category',
            field=models.ImageField(default='category_images/images.png', upload_to='catagory_images/'),
        ),
    ]
