# Generated by Django 5.1.5 on 2025-02-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_category',
            field=models.ImageField(default='catagory_images/images.png', upload_to='catagory_images/'),
        ),
    ]
