# Generated by Django 4.2 on 2025-02-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/image_product.jpg', upload_to='product_images/'),
        ),
    ]
