# Generated by Django 4.2 on 2025-02-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'หมวดหมู่สินค้า', 'verbose_name_plural': 'หมวดหมู่สินค้า'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'สินค้า', 'verbose_name_plural': 'สินค้า'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'รูปภาพสินค้า', 'verbose_name_plural': 'รูปภาพสินค้า'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'หน่วยสินค้า', 'verbose_name_plural': 'หน่วยสินค้า'},
        ),
        migrations.AlterField(
            model_name='category',
            name='check_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_category',
            field=models.ImageField(default='category_images/default.png', upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='check_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='date_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
