# Generated by Django 4.2 on 2025-02-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_category',
            field=models.ImageField(default='category_images/images.png', upload_to='category_images/'),
        ),
    ]
