# Generated by Django 5.1.5 on 2025-02-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_supplier_alter_inventory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('restock', 'Restock'), ('shop', 'shop'), ('sale', 'Sale'), ('out', 'out'), ('return', 'Return'), ('instock', 'instock')], max_length=20),
        ),
    ]
