# Generated by Django 4.2 on 2025-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_stockmovement_stockinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_product',
            field=models.ImageField(default='image_product.jpg', upload_to='product_images/'),
        ),
    ]
