# Generated by Django 4.2 on 2025-03-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.ImageField(default='product_images/image_product.jpg', upload_to='product_images/'),
        ),
    ]
