# Generated by Django 4.2 on 2025-03-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='check_data',
            field=models.BooleanField(default=True),
        ),
    ]
