# Generated by Django 4.2 on 2025-03-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_check_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, default='ชิ้น', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.unit'),
        ),
    ]
